// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBsOOj1OPIaweGlYRRdF3UvzBpLje7ZU',
    appId: '1:380566837985:web:a71ca4a161eb485b69f5a0',
    messagingSenderId: '380566837985',
    projectId: 'quizzle-application',
    authDomain: 'quizzle-application.firebaseapp.com',
    storageBucket: 'quizzle-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqjHnfaLC8wZj-e3R_QXNMlCT74kf-co',
    appId: '1:380566837985:android:7c310ff52cc5bc7e69f5a0',
    messagingSenderId: '380566837985',
    projectId: 'quizzle-application',
    storageBucket: 'quizzle-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzMWqYZmZ82xCbYp6lYhcQpSJx2ITwx4',
    appId: '1:380566837985:ios:0a29152c75aeac9869f5a0',
    messagingSenderId: '380566837985',
    projectId: 'quizzle-application',
    storageBucket: 'quizzle-application.appspot.com',
    androidClientId: '380566837985-1pkpbapulk95alkhsgmgosscjvsn3p6g.apps.googleusercontent.com',
    iosClientId: '380566837985-cd4i63t35n5ulgdbc67kuqpkrvj8uki7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzle',
  );
}
